#!/usr/bin/env node
/**
 * extract_sitemap_data.js
 * ===================================================================
 * One-time (and re-runnable) extraction step for the sitemap.html
 * performance fix.
 *
 * WHY THIS EXISTS: sitemap.html's link grid (394,749 routes) was never
 * generated by any script in scripts/ - generate-sitemap.js only owns
 * sitemap.xml and the static #sitemapRouteCount text; generate_sitemap.js
 * is an older, structurally different generator that doesn't match the
 * live page-card/category grouping at all. The grid's actual data has no
 * single source of truth to regenerate from safely, so rather than
 * re-deriving 394,749 URLs from scratch (real risk of silently dropping
 * or mis-labeling pages - the exact discoverability harm we must avoid),
 * this script extracts the EXISTING, already-correct href+label pairs
 * directly out of the current sitemap.html and splits them into small
 * per-category JSON files. Every URL and label in the output is copied
 * verbatim from what's already live - nothing is regenerated or guessed.
 *
 * Output: sitemap-data/<slug>.json  - one array of [href, label] pairs
 *                                     per category (tuples, not objects,
 *                                     to keep these files as small as
 *                                     possible - label text alone across
 *                                     394,749 routes is the bulk of the
 *                                     payload)
 *         sitemap-data/index.json   - ordered list describing exactly
 *                                     how to rebuild the grid: each
 *                                     category (slug, name, count) and
 *                                     each ad-placeholder block, in the
 *                                     original sequence, so the ad slots
 *                                     land in exactly the same positions
 *                                     they occupy today.
 *
 * Usage: node scripts/extract_sitemap_data.js [path/to/sitemap.html] [outDir]
 */
'use strict';
const fs = require('fs');
const path = require('path');

const sitemapPath = path.resolve(process.argv[2] || 'sitemap.html');
const outDir = path.resolve(process.argv[3] || 'sitemap-data');

const html = fs.readFileSync(sitemapPath, 'utf8');

// Isolate just the grid: from the sitemap-grid opening tag to its closing
// </section>, so we never touch head/hero/search-bar/footer/script markup.
const gridStart = html.indexOf('<section class="page-grid sitemap-grid"');
if (gridStart === -1) throw new Error('Could not find <section class="page-grid sitemap-grid"> in ' + sitemapPath);
const mainCloseIdx = html.indexOf('</main>', gridStart);
if (mainCloseIdx === -1) throw new Error('Could not find closing </main> after the grid');
const grid = html.slice(gridStart, mainCloseIdx);

// Walk the grid top-to-bottom, matching either a page-card or an
// in-content-ad block, in whatever order they actually appear.
const blockRe = /<section class="page-card">([\s\S]*?)<\/section>|<section class="in-content-ad adsense-placeholder" data-ad-placement="([^"]*)"[^>]*>([\s\S]*?)<\/section>/g;

const indexEntries = [];
let match;
let cardCount = 0;
let adCount = 0;

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

while ((match = blockRe.exec(grid)) !== null) {
  if (match[1] !== undefined) {
    // --- page-card ---
    const cardHtml = match[1];
    const nameMatch = cardHtml.match(/<h2>([^<]*)<\/h2>/);
    const name = nameMatch ? nameMatch[1] : ('CATEGORY_' + (cardCount + 1));

    const linkRe = /<li><a href="([^"]*)">([^<]*)<\/a><\/li>/g;
    const links = [];
    let linkMatch;
    while ((linkMatch = linkRe.exec(cardHtml)) !== null) {
      links.push([linkMatch[1], linkMatch[2]]);
    }

    // Slug from the category's own index link (first entry), e.g.
    // https://theuniversalconverter.com/agriculture/ -> "agriculture".
    // Falls back to a slugified name if that pattern isn't found.
    let slug = null;
    if (links.length) {
      const m = links[0][0].match(/\/([a-z0-9-]+)\/?$/i);
      if (m) slug = m[1].toLowerCase();
    }
    if (!slug) slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

    fs.writeFileSync(path.join(outDir, slug + '.json'), JSON.stringify(links));
    indexEntries.push({ type: 'category', slug, name, count: links.length });
    cardCount++;
  } else {
    // --- ad placeholder ---
    const placement = match[2] || '';
    const adHtml = match[3] || '';
    const labelMatch = adHtml.match(/<p>([^<]*)<\/p>/);
    indexEntries.push({
      type: 'ad',
      placement,
      label: labelMatch ? labelMatch[1] : ''
    });
    adCount++;
  }
}

fs.writeFileSync(path.join(outDir, 'index.json'), JSON.stringify(indexEntries, null, 2));

const totalLinks = indexEntries.reduce((sum, e) => sum + (e.count || 0), 0);
console.log(`Extracted ${cardCount} categories (${totalLinks} total links) and ${adCount} ad placements.`);
console.log(`Wrote ${outDir}/index.json + ${cardCount} per-category JSON files.`);
